name: 'FORGE AI DevOps Copilot'
description: 'Analyze CI failures and PRs using FORGE AI Agents'
author: 'KhulnaSoft'
inputs:
  github_token:
    description: 'GitHub Token for accessing PRs and logs'
    required: true
    default: ${{ github.token }}
  openai_api_key:
    description: 'OpenAI API Key for reasoning'
    required: true
  ai_provider:
    description: 'AI provider to use (OpenAI or Ollama)'
    required: false
    default: 'OpenAI'
  ollama_url:
    description: 'URL for Ollama'
    required: false
    default: 'http://localhost:11434'

runs:
  using: 'composite'
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    
    - name: Install Dependencies
      run: npm install
      shell: bash
      working-directory: ${{ github.action_path }}

    - name: Run FORGE Agent
      run: |
        node src/agent/cli.js
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        OPENAI_API_KEY: ${{ inputs.openai_api_key }}
        GITHUB_OWNER: ${{ github.repository_owner }}
        GITHUB_REPO: ${{ github.event.repository.name }}
        FORGE_PROVIDER: ${{ inputs.ai_provider }}
        OLLAMA_URL: ${{ inputs.ollama_url }}

branding:
  icon: 'cpu'
  color: 'orange'
  # Note: Marketplace uses predefined icons. 'cpu', 'terminal', or 'zap' are good fits.
