// src/agent/formatter/markdown.ts

export class MarkdownReportGenerator {
    /**
     * Generates a high-impact Markdown summary for GitHub Job Summaries and PR Comments.
     */
    static generateReport(data: {
        summary: string;
        security: string;
        performance: string;
        workflow: string;
        test: string;
        fix_file: string;
        fix_content: string;
        owner: string;
        repo: string;
        line?: number;
    }): string {
        const extensionId = "khulnasoft.forge-ci";
        const targetLine = data.line || 1;
        const deepLink = `vscode://${extensionId}/open-fix?file=${encodeURIComponent(data.fix_file)}&line=${targetLine}&repo=${encodeURIComponent(data.owner + '/' + data.repo)}`;

        return `
# 🔥 FORGE: AI DevOps Analysis

${data.summary}

## 🤖 Expert Reasoning

<details>
<summary><b>🛡️ Security Analyst</b></summary>
${data.security || "No critical security risks identified."}
</details>

<details>
<summary><b>🚀 Performance Analyst</b></summary>
${data.performance || "Logic appears optimal."}
</details>

<details>
<summary><b>🧹 Workflow Master</b></summary>
${data.workflow || "Workflow configuration is healthy."}
</details>

<details>
<summary><b>🧪 Test & Coverage</b></summary>
${data.test || "Coverage looks consistent."}
</details>

## 🛠 Suggested Fix

**File:** \`${data.fix_file}\` (Line ${targetLine})

\`\`\`${this.getLanguage(data.fix_file)}
${data.fix_content}
\`\`\`

### ⚡ Quick Actions
- [🔍 Open & Fix in VS Code](${deepLink})
- [📁 View Action Summary](https://github.com/${data.owner}/${data.repo}/actions)

---
*Generated by [FORGE AI](https://github.com/marketplace/actions/forge-ai)*
        `;
    }

    private static getLanguage(filename: string): string {
        const ext = filename.split('.').pop() || '';
        const map: Record<string, string> = {
            'ts': 'typescript',
            'js': 'javascript',
            'py': 'python',
            'go': 'go',
            'yml': 'yaml',
            'yaml': 'yaml'
        };
        return map[ext] || '';
    }
}
